# Generated by Django 4.1.2 on 2022-10-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Смерека', max_length=250)),
                ('is_club_member', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='карабин', max_length=250)),
                ('path', models.CharField(default='горное', max_length=50)),
                ('unique', models.BooleanField(default=True)),
                ('number', models.IntegerField(blank=True, default=1)),
                ('price_per_day', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('price_for_members', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(default='Смерека', max_length=250)),
                ('type_of_hike', models.CharField(choices=[('ПВД', 'noncategoried'), ('Лыжный', 'лыжный'), ('Горный', 'горный'), ('Водный', 'водный'), ('Пеший', 'пеший'), ('Спелео', 'спелео'), ('Вело', 'вело')], default='ПВД', max_length=15)),
                ('start_date', models.DateField(default='2021-01-02')),
                ('end_date', models.DateField(default='2021-01-02')),
                ('price', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('equipment', models.ManyToManyField(to='kapterka.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='GroupComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realMembers', models.IntegerField(default=0)),
                ('students', models.IntegerField(default=0)),
                ('newOnes', models.IntegerField(default=0)),
                ('others', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2021-01-02')),
                ('end_date', models.DateField(default='2021-01-02')),
                ('archived', models.BooleanField(default=False)),
                ('equipment', models.ManyToManyField(to='kapterka.equipment')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='kapterka.contact')),
            ],
        ),
        migrations.CreateModel(
            name='RentedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=1)),
                ('type_of_accounting', models.CharField(choices=[('UesrAccounting', 'GroupAccounting'), ('GroupAccounting', 'GroupAccounting')], default='GroupAccounting', max_length=15)),
                ('equipment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='kapterka.equipment')),
                ('group_accounting', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kapterka.groupaccounting')),
                ('user_accounting', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kapterka.useraccounting')),
            ],
        ),
        migrations.AddField(
            model_name='groupaccounting',
            name='group_composition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='kapterka.groupcomposition'),
        ),
        migrations.AddField(
            model_name='groupaccounting',
            name='responsible_person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person', to='kapterka.contact'),
        ),
    ]
