# Generated by Django 3.2.7 on 2021-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikeaccounting',
            name='end_date',
            field=models.DateField(default='2021-01-02'),
        ),
        migrations.AddField(
            model_name='hikeaccounting',
            name='start_date',
            field=models.DateField(default='2021-01-02'),
        ),
    ]
