# Generated by Django 3.2.7 on 2021-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0003_alter_equipment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikeaccounting',
            name='lead_name',
            field=models.CharField(default='Смерека', max_length=250),
        ),
    ]
