# Generated by Django 3.2.7 on 2021-09-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0005_rename_hikeaccounting_groupaccounting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Contact',
        ),
    ]
