# Generated by Django 3.2.7 on 2021-10-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0007_auto_20210930_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=1)),
                ('type_of_accounting', models.CharField(choices=[('UesrAccounting', 'GroupAccounting'), ('GroupAccounting', 'GroupAccounting')], default='GroupAccounting', max_length=15)),
                ('eqipment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='KaptyorkaApp.equipment')),
                ('group_accounting', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='KaptyorkaApp.groupaccounting')),
                ('user_accounting', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='KaptyorkaApp.useraccounting')),
            ],
        ),
    ]
