# Generated by Django 3.2.7 on 2021-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0008_rentedequipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentedequipment',
            old_name='eqipment',
            new_name='equipment',
        ),
    ]
