# Generated by Django 3.2.7 on 2021-11-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0011_groupcomposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcomposition',
            name='group_accounting',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='KaptyorkaApp.groupaccounting'),
        ),
    ]
