# Generated by Django 3.2.7 on 2021-09-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='карабин', max_length=250)),
                ('type', models.CharField(default='горное', max_length=50)),
                ('subtype', models.CharField(default='горное', max_length=50)),
                ('unique', models.BooleanField(default=True)),
                ('number', models.IntegerField(blank=True, default=1)),
                ('price_per_day', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('price_for_members', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Смерека', max_length=250)),
                ('is_club_member', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2021-01-02')),
                ('end_date', models.DateField(default='2021-01-02')),
                ('archived', models.BooleanField(default=False)),
                ('equipment', models.ManyToManyField(to='KaptyorkaApp.Equipment')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='KaptyorkaApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='HikeAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(choices=[('ПВД', 'noncategoried'), ('Лыжный', 'лыжный'), ('Горный', 'горный'), ('Водный', 'водный'), ('Пеший', 'пеший'), ('Спелео', 'спелео'), ('Вело', 'вело')], default='ПВД', max_length=15)),
                ('type_of_hike', models.CharField(choices=[('ПВД', 'noncategoried'), ('Лыжный', 'лыжный'), ('Горный', 'горный'), ('Водный', 'водный'), ('Пеший', 'пеший'), ('Спелео', 'спелео'), ('Вело', 'вело')], default='ПВД', max_length=15)),
                ('group_members', models.CharField(choices=[('ПВД', 'noncategoried'), ('Лыжный', 'лыжный'), ('Горный', 'горный'), ('Водный', 'водный'), ('Пеший', 'пеший'), ('Спелео', 'спелео'), ('Вело', 'вело')], default='ПВД', max_length=1000)),
                ('archived', models.BooleanField(default=False)),
                ('equipment', models.ManyToManyField(to='KaptyorkaApp.Equipment')),
                ('responsible_person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person', to='KaptyorkaApp.profile')),
            ],
        ),
    ]
