# Generated by Django 3.2.7 on 2021-09-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0002_auto_20210913_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
