# Generated by Django 3.2.7 on 2021-09-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0004_alter_hikeaccounting_lead_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HikeAccounting',
            new_name='GroupAccounting',
        ),
    ]
