# Generated by Django 3.2.7 on 2021-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0009_rename_eqipment_rentedequipment_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccounting',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
