# Generated by Django 3.2.7 on 2021-11-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0012_groupcomposition_group_accounting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupaccounting',
            name='group_members',
        ),
        migrations.RemoveField(
            model_name='groupcomposition',
            name='group_accounting',
        ),
        migrations.AddField(
            model_name='groupaccounting',
            name='group_composition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='KaptyorkaApp.groupcomposition'),
        ),
    ]
